version: "3" 
services:
  elasticsearch: 
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    container_name: elasticsearch 
    environment:
        - discovery.type=single-node
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
        memlock:
            soft: -1
            hard: -1
    volumes:
        - data:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    networks:
        - elastic
    labels:
        - co.elastic.logs/module=elasticsearch
        - co.elastic.metrics/module=elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.11.2
    container_name: kibana 
    ports:
        - 5601:5601
    depends_on:
        - elasticsearch
    environment:
        ELASTICSEARCH_URL: http://elasticsearch:9200
        ELASTICSEARCH_HOSTS: http://elasticsearch:9200 
    networks:
        - elastic

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    ports:
        - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=podcast
    volumes:
        - pgdata:/var/lib/postgresql/data
    networks:
        - elastic

volumes:
  data:
    driver: local

  pgdata:
    driver: local

networks:
  elastic:
    driver: bridge

